### ISSUE TITLE
백엔드 GitHub Actions workflow 디렉토리 한정

### ISSUE THREAD

**Issue by solo5star** [woowacourse-teams/2023-yozm-cafe#28]
## 📑 논의 사항
* 프론트엔드 PR인데 백엔드 workflow가 실행이 된다?
* `paths`를 추가하여 백엔드 폴더에 push가 되었을 때만 worflow가 실행되도록 하면 어떨까 제안 드립니다.
* 의견 있을 시 댓글 부탁드립니다.

### 이렇게 수정하면 좋겠어요!
```yaml
on:
  push:
    branches: [ main ]
    paths: server/**
  pull_request:
    branches: [ main ]
    paths: server/**
```

## 🎸 기타사항
관련 공식문서: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths
