### ISSUE TITLE
MySQL 환경용 도커 컴포즈 파일을 수정한다

### ISSUE THREAD

**Issue by nuyh99** [woowacourse-teams/2023-yozm-cafe#63]
## 📑 작업 사항
- /server/docker/docker-compose.yml 수정

## 📝 에러 내용
- 팀시티 측에서 빌드를 할 때 MySQL 환경이 필요한데 도커 컴포즈를 통한 MySQL 컨테이너가 살아있지 않음

## 👾 에러 원인
- 서버는 arm 환경인데 docker-compose의 플랫폼이 amd로 돼있어 동작하지 않음

## 🎸 기타 사항
```yml
version: "3.8"
services:
  mysql:
    platform: linux/arm64/v8
    image: library/mysql:8.0.33
    ports:
      - 20000:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yozm-cafe
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    command: [ "mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci" ]
```
위와 같이 도커 컴포즈 파일을 변경해야 함

- 손으로 직접 TeamCity Agent 내에 위 yml로 컨테이너를 띄운 뒤 테스트 해보니 CI/CD 워크플로우 성공
- docker-compose 파일만 수정하면 아래의 스텝으로 빌드 동안만 띄우고 빌드 이후 자동 삭제 가능
![image](https://github.com/woowacourse-teams/2023-yozm-cafe/assets/93072571/71c3bee1-cf65-4613-b454-2818f0c1932b)
